deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  repo: popcorn-morbihan/popcorn-morbihan.github.io
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master