language: node_js
node_js:
  - 10
branches:
  only:
    - master

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm install

script:
  - npm run generate

deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  target-branch: master
  repo: popcorn-morbihan/popcorn-morbihan.github.io
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master